### ISSUE TITLE
error when loading 

### ISSUE THREAD

**Issue by eliteproxy7** [bergben/ng2-scrollimate#1]
ERROR in ../src/app/app.component.ts (13,9): Cannot find name 'trigger'.)
../src/app/app.component.ts (14,13): Cannot find name 'state'.)
../src/app/app.component.ts (14,31): Cannot find name 'style'.)
../src/app/app.component.ts (18,13): Cannot find name 'state'.)
../src/app/app.component.ts (18,29): Cannot find name 'style'.)
../src/app/app.component.ts (22,13): Cannot find name 'transition'.)
../src/app/app.component.ts (22,39): Cannot find name 'animate'.)
../src/app/app.component.ts (23,13): Cannot find name 'transition'.)
../src/app/app.component.ts (23,41): Cannot find name 'animate'.)

**Comment by bergben** [comment]
Hi @eliteproxy7  
You have to import those.
` import { trigger, style, animate, transition, state } from '@angular/core';`

**Comment by eliteproxy7** [comment]
thank you! that worked great!

question, how can i have it where the items that only are already in the viewport to be avtive and have a class be attached to them?

great component btw!

**Comment by eliteproxy7** [comment]
also i know i may be doing this wrong but what if i have lets say 20 <divs> with the exact same  percentElement how can I do that? right now i have to create 20 different percentElement's (percentElement1, percentElement2 etc ) in scrollimateOptions

**Comment by bergben** [comment]
> question, how can i have it where the items that only are already in the viewport to be avtive and have a class be attached to them?

I am not sure if I understand your question but you can add css classes like described here: https://github.com/bergben/ng2-scrollimate#adding-css-classes

>also i know i may be doing this wrong but what if i have lets say 20 with the exact same percentElement how can I do that? right now i have to create 20 different percentElement's (percentElement1, percentElement2 etc ) in scrollimateOptions

If they all trigger at the same percent, then why don't you just create one and 
apply that for all `[@elementState]="scrollimateOptions.mySameOldOption.currentState" [scrollimate]="scrollimateOptions.mySameOldOption"` 
Or do you mean the state / other values are different but the percentElement would always be the same? In that case you'd really have to create 20 different percentElement's in scrollimateOptions :(
