### ISSUE TITLE
Trigger by div in viewport

### ISSUE THREAD

**Issue by tschaka1904** [bergben/ng2-scrollimate#2]
Is there a way to trigger an event if a div is in the viewport? For example, if you have a div: 
`<div id="awesomeDiv">This is an awesome div</div>`
and it is coming into the viewport an event is triggered? 

Or event better, if the `awesomeDiv` the upper 10% of the viewport?

What I'm trying to to here is, to mimic a kind of side-nav of Zurb Foundation: http://foundation.zurb.com/sites/docs/magellan.html

**Comment by bergben** [comment]
You can subscribe to the `scrollimate` event which will fire when the state changes. https://github.com/bergben/ng2-scrollimate#scrollimate 

So basically you could just use https://github.com/bergben/ng2-scrollimate#percentelement and set it to 90%

```
  scrollimateOptions: any = {
       myScrollimation: {
              currentState: "inactive", //currentState is required
              states: [
                  { //PRIORITY 1
                      method: "percentElement",
                      value: 90,
                      state: "active",
                  },
                  { //PRIORITY 2
                      method: "default",
                      state: "inactive"
                  }
              ]
          }
  }
```

```
<div id="awesomeDiv" [scrollimate]="scrollimateOptions.myScrollimation" (scrollimate)="awesomeDivStateChanged($event)">This is an awesome div</div>
```

```
   public awesomeDivStateChanged(event){
      if(event.state==="active"){
        //awesomeDiv is only 10% away from the upper viewport (or less)
      }
      else{
        //awesomeDiv is more than 10% away from the upper viewport
      }
   }
```

**Comment by tschaka1904** [comment]
Thanks a lot @bergben! Very helpful.
