### ISSUE TITLE
Only have animations play once

### ISSUE THREAD

**Issue by jonstuebe** [bergben/ng2-scrollimate#3]
Is there an option in the settings to disable "active" elements from going "inactive"? I basically only want the animations to run once.

**Comment by bergben** [comment]
You could just use a custom animation where the transition from active to inactive takes 0ms or some other custom animation I guess.

**Comment by bergben** [comment]
Unfortunately there is no such option. You would have to listen to the events and when set to active you manipulate your scrollimateOptions so that the defaultState for the element is `active`...
